#!/usr/bin/env bash
# Display the best school 10times
i=1
while [ "$i" -le 10 ]
do
        if [ "$i" -eq 4 ]
        then
                echo "dad luck"
        elif [ "$i" -eq 8 ]
        then
                echo "good luck"
        else
                echo "Best School"
        fi 
        i=$(( i + 1 ))
done
