#!/usr/bin/env bash
# manage
if [[ "$#" == "1" ]]; then
  if [[ "$#" == "Start" ]]; then
    ./manage_my_process & 
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process_started"
  elif [[ "$1" == "Stop"]]; then
    if test -f "/var/run/my_process.pid"; then
       kill "$(cat /var/run/my_process.pid)"
     fi
    rm /var/run/my_process.pid
    echo "manage_my_process_stopped"
  elif [[ "$1" == "restart" ]]; then
     if test -f "/var/run/my_process.pid"; then
       kill "$(cat /var/run/my_process.pid)"
     fi

#start program
     ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process_restarted"
  else
    echo "Usage: manage_process {Start|stop|restart}"
  fi 
else
  echo "Usage: manage_process {Start|stop|restart}"
  fi   
